2021-03-31 11:55:07.352 - INFO - 18532 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 11:55:07.367 - INFO - 18532 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 11:55:07.367 - INFO - 18532 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:105 - Start data validation.
2021-03-31 11:55:07.383 - CRITICAL - 18532 - azureml.train.automl._experiment_drivers.driver_utilities.log_traceback:227 - Type: Unclassified
Class: ValueError
Message: experiment_id should not be None.
Traceback:
  File "driver_utilities.py", line 114, in validate_input
    validation_results = experiment_state.jasmine_client.post_validate_service(parent_run_dto)
  File "jasmine_client.py", line 59, in post_validate_service
    return self._execute_with_experimentid_arguments(
  File "experiment_client.py", line 261, in _execute_with_experimentid_arguments
    raise ValueError("experiment_id should not be None.")

ExceptionTarget: Unspecified
2021-03-31 11:55:07.383 - WARNING - 18532 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:122 - Validation service meet exceptions, continue training now.
2021-03-31 13:06:35.986 - INFO - 17184 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 13:06:36.009 - INFO - 17184 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 13:06:36.010 - INFO - 17184 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:105 - Start data validation.
2021-03-31 13:06:36.030 - CRITICAL - 17184 - azureml.train.automl._experiment_drivers.driver_utilities.log_traceback:227 - Type: Unclassified
Class: ValueError
Message: experiment_id should not be None.
Traceback:
  File "driver_utilities.py", line 114, in validate_input
    validation_results = experiment_state.jasmine_client.post_validate_service(parent_run_dto)
  File "jasmine_client.py", line 59, in post_validate_service
    return self._execute_with_experimentid_arguments(
  File "experiment_client.py", line 261, in _execute_with_experimentid_arguments
    raise ValueError("experiment_id should not be None.")

ExceptionTarget: Unspecified
2021-03-31 13:06:36.031 - WARNING - 17184 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:122 - Validation service meet exceptions, continue training now.
2021-03-31 15:13:45.717 - INFO - 21528 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 15:13:45.740 - INFO - 21528 - azureml.automl.core.dataset_utilities._save_datasets_to_json:148 - JSON serialization of input of type <class 'NoneType'> is un-supported.
2021-03-31 15:13:45.741 - INFO - 21528 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:105 - Start data validation.
2021-03-31 15:13:45.764 - CRITICAL - 21528 - azureml.train.automl._experiment_drivers.driver_utilities.log_traceback:227 - Type: Unclassified
Class: ValueError
Message: experiment_id should not be None.
Traceback:
  File "driver_utilities.py", line 114, in validate_input
    validation_results = experiment_state.jasmine_client.post_validate_service(parent_run_dto)
  File "jasmine_client.py", line 59, in post_validate_service
    return self._execute_with_experimentid_arguments(
  File "experiment_client.py", line 261, in _execute_with_experimentid_arguments
    raise ValueError("experiment_id should not be None.")

ExceptionTarget: Unspecified
2021-03-31 15:13:45.764 - WARNING - 21528 - azureml.train.automl._experiment_drivers.driver_utilities.validate_input:122 - Validation service meet exceptions, continue training now.
